### ISSUE TITLE
Implement Execution Log

### ISSUE THREAD

**Issue by ivanakcheurov** [ivanakcheurov/desh.net#1]
Implement a structured execution log.
```yaml
engine_version: 0.1.1
desh_md5: fd21637312641af
desh: | 
    hair_color:
      - [grey, blond]: Angel
      - brown: Sweet
      - red:
          hair_length:
            - long: Lava
            - medium: Chocolate
            - short: Emerald
steps:
  - step_number: 1
    timestamp: 2019-02-09 10:31:59.457
    desh_span: 1,1 - 1,11
    source_code_file: Desh.Parsing.DeshParser.cs
    source_code_line: 172
    source_code_member: ExecuteComparator
    type: expand_variable
    variable_name: hair_color
    variable_value: brown
  - step_number: 2
    timestamp: 2019-02-09 10:31:59.458
    desh_span: 2,5 - 2,18
    source_code_file: Desh.Parsing.DeshParser.cs
    source_code_line: 246
    source_code_member: ExecuteOperation
    type: evaluate_operation
    operation_name: equalsAny
    first_value: brown
    parameters: [grey, blond]
    result: true
```
