### ISSUE TITLE
Implement decision-centric desh

### ISSUE THREAD

**Issue by ivanakcheurov** [ivanakcheurov/desh.net#2]
Implement desh that allows to start with decision first and then specify their conditions
```yaml
decide:
  - bus:
      passengers_count:
        - greater_than: 8
  - van:
      anyOf:
        - passengers_count:
            - greater_than: 4
        - suitcases_count:
            - greater_than: 3
  - car
```
