### ISSUE TITLE
Support kiosk/wizard/survey interaction

### ISSUE THREAD

**Issue by ivanakcheurov** [ivanakcheurov/desh.net#4]
# Request
Support kiosk, wizard or survey type of interaction with Desh engine.

# Example
Let's take an example of a travel agency.
The operator needs to know if the client needs a visa to travel to the country of destination.
The business rules that describe if visa is needed are encoded in the following Desh:
```yaml
nationality:
  - [NL]:
      destination:
        - US: electronic_online_visa
        - UA:
            duration_of_stay:
              - greater_than: 90 days
                decide: paper_visa
              - else: no_visa
  - [UA]:
      destination:
        - US: paper_visa
        - NL:
            biometric_passport:
              - yes: no_visa
              - no: paper_visa
```
In this case, we don't need to ask a Dutch (NL) client if she has a biometric passport when flying to the US.

Support a question-answer style of interaction with Desh engine:
- _kiosk:_ What is your nationality?
- _user:_ Dutch (NL).
- _kiosk:_ What is your destination?
- _user:_ United States of America (US).
- _kiosk:_ You need an electronic visa that can be obtained online.
